### ISSUE TITLE
你这个用的是SonarQube 哪个版本? sonarqube-8.6.1.40680 放完jar后起不来

### ISSUE THREAD

**Issue by yizems** [Thorbear/sonar-android#27]
```cmd
2021.02.23 09:59:55 INFO  web[][o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
2021.02.23 09:59:55 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: Fail to load plugin Android Lint [androidLint]
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:80)
	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:557)
	at org.sonar.server.platform.PlatformImpl.start(PlatformImpl.java:213)
	at org.sonar.server.platform.PlatformImpl.startLevel34Containers(PlatformImpl.java:187)
	at org.sonar.server.platform.PlatformImpl.access$500(PlatformImpl.java:46)
	at org.sonar.server.platform.PlatformImpl$1.lambda$doRun$0(PlatformImpl.java:120)
	at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.runIfNotAborted(PlatformImpl.java:370)
	at org.sonar.server.platform.PlatformImpl$1.doRun(PlatformImpl.java:120)
	at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.run(PlatformImpl.java:354)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/batch/Sensor
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
	at org.sonar.classloader.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:37)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	at no.thorbear.sonar.plugins.android.AndroidPlugin.getExtensions(AndroidPlugin.kt:23)
	at org.sonar.api.SonarPlugin.define(SonarPlugin.java:51)
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:70)
	... 9 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonar.api.batch.Sensor
	at org.sonar.classloader.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:41)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	... 24 common frames omitted

```

**Comment by yizems** [comment]
8.6 已经内置了 android lint 的支持, 配置下就行,无需插件;


```
classpath "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:3.1.1"
apply plugin: "org.sonarqube"
sonarqube {
    androidVariant "devRelease"
    properties {
        property 'sonar.projectKey', 'app'
        property 'sonar.host.url', 'http://127.0.0.1:9000'
        property 'sonar.login', 'xxxxxx'
        property "sonar.profile", "Android Lint"
        property "sonar.sources", "./src"
        property "sonar.androidLint.reportPaths", rootDir.absolutePath + "/app/build/reports/lint-results-devRelease.xml"
        property 'sonar.sourceEncoding', 'UTF-8'
    }
}

```

**Comment by cocpublic** [comment]
> 8.6 已经内置了 android lint 的支持, 配置下就行,无需插件;
> 
> ```
> classpath "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:3.1.1"
> apply plugin: "org.sonarqube"
> sonarqube {
>     androidVariant "devRelease"
>     properties {
>         property 'sonar.projectKey', 'app'
>         property 'sonar.host.url', 'http://127.0.0.1:9000'
>         property 'sonar.login', 'xxxxxx'
>         property "sonar.profile", "Android Lint"
>         property "sonar.sources", "./src"
>         property "sonar.androidLint.reportPaths", rootDir.absolutePath + "/app/build/reports/lint-results-devRelease.xml"
>         property 'sonar.sourceEncoding', 'UTF-8'
>     }
> }
> ```

内置的仅仅只能导入，lint的问题没法想常规的issue一样管理
